#!/bin/sh
# Copyright 2023, Sam Hartman
# This code may be redistributed under the same terms as Linux Pam
# itself, or at your pution, under the GNU General Public License,
# version 3. 

set -e
useradd -s /bin/bash pam_test 2>&1 || true
python3 debian/tests/pam-test.py
userdel pam_test ||true
